services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/foodieApp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE=5
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_FETCH_SIZE=50
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=5
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=2
      - JAVA_OPTS=-Xmx256m -Xms128m -XX:+UseContainerSupport -XX:MaxRAMPercentage=50
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 200M
    depends_on:
      db:
        condition: service_healthy
    networks:
      - foodie-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=foodieApp
      - MYSQL_ROOT_HOST=%
      - MYSQL_INNODB_BUFFER_POOL_SIZE=64M
      - MYSQL_INNODB_LOG_FILE_SIZE=16M
      - MYSQL_MAX_CONNECTIONS=10
      - MYSQL_PERFORMANCE_SCHEMA=OFF
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 300M
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - foodie-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 1s
      timeout: 20s
      retries: 10

volumes:
  mysql-data:

networks:
  foodie-network:
    driver: bridge
